[
  {
  "id": "1",
  "category": "respiratory",
  "diseases": "allergies",
  "position": "eyes, nose, thoat, skin",
  "primary_symptoms": "rash, difficulty breathing, swelling, wheezing, hives",
  "time": "chronic",
  "unique": "hives, rash after contact with object, rash after contact with food",
  "emergency": "difficulty breathing",
  "home": "otc antihistamines"
},
{
  "id": "2",
  "category": "gastrointestinal",
  "diseases": "appendicitis",
  "position": "groin, stomach",
  "primary_symptoms": "pain, fever, appetite loss",
  "time": "acute",
  "unique":"umbilical pain" ,
  "emergency": "vomiting",
  "home": ""
},
{
  "id": "3",
  "category": "respiratory",
  "diseases": "asthma",
  "position": "chest, throat, nose, skin",
  "primary_symptoms": "wheezing, difficulty breathing, loss of consciousness",
  "time": "chronic",
  "unique": "wheezing, difficulty breathing, dry rash",
  "emergency": "difficulty breathing, chest pain, chest tightness, blue lips, blue fingertips, loss of consiousness",
  "home": "avoid cold air, avoid allergy triggers, avoid nicotine, avoid tobacco"
},
{
  "id": "4",
  "category": "infection",
  "diseases": "athletes Foot",
  "position": "feet, leg",
  "primary_symptoms": "Itchiness",
  "time": "chronic",
  "unique": "itching",
  "emergency": "swelling" ,
  "home": "anti-fungal cream"
},
{
  "id": "5",
  "category": "neurological",
  "diseases": "benign paroxysmal postiional vertigo",
  "position": "head, ear, eyes",
  "primary_symptoms": "dizziness, nausea, vomiting",
  "time": "chronic" ,
  "unique": "dizziness",
  "emergency": "traumatic fall" ,
  "home": ""
},
{
  "id": "6",
  "category": "cancer",
  "diseases": "Breast Cancer",
  "position": "chest",
  "primary_symptoms": "nipple retracton, lump, rash",
  "time": "chronic",
  "unique": "skin changes, nipple inversion, bloody discharge, lump",
  "emergency": "skin changes, nipple inversion, bloody discharge, lump",
  "home": "contact your doctor"
},
{
  "id": "7",
  "category": "respiratory",
  "diseases": "Bronchitis",
  "position": "chest",
  "primary_symptoms": "cough, difficulty breathing, wheezing, fatigue",
  "time": "acute",
  "unique": "mucous, constant cough, wheezing",
  "emergency": "weight loss, blood after cough",
  "home": "otc painkillers, avoid nicotine, avoid tobacco, hydrate"
},
{
  "id": "8",
  "category":"musculoskeletal",
  "diseases": "Bursitis",
  "position": "knee, elbow, shoulder",
  "primary_symptoms": "swelling, reddness, warmth",
  "time": "acute",
  "unique": "due to trauma, due to repetitive movements",
  "emergency": "fever",
  "home": "otc painkillers"
},
{
  "id": "9",
  "category": "infection",
  "diseases": "chicken-pox",
  "position": "full-body",
  "primary_symptoms": "fever, malaise, headache, myalgia, rash",
  "time":"acute" ,
  "unique": "no vaccination",
  "emergency": "coma",
  "home": "calamine lotion"
},
{
  "id": "10",
  "category": "respiratory",
  "diseases": "Cluster Headache",
  "position": "head",
  "primary_symptoms": "pain, vomiting, red eyes, vision loss",
  "time": "chronic",
  "unique": "incapacitation",
  "emergency": "incapacitation",
  "home": "OTC painkillers"
},
{
  "id": "11",
  "category":"infection",
  "diseases": "common cold",
  "position": "nose, throat, sinus",
  "primary_symptoms": "sneezing, cough, congestion, runny nose",
  "time": "acute",
  "unique": "",
  "emergency":"" ,
  "home": ""
},
{
  "id": "12",
  "category":"infection",
  "diseases": "Coronavirus/ COVID-19",
  "position": "full body, chest, head, stomach",
  "primary_symptoms": "shortness of breath, cough, Fever, pain", 
  "time":"acute, chroinic" ,
  "unique": "no vaccination",
  "emergency": "loss of breath",
  "home": ""
},
{
  "id": "13",
  "category":"neurological",
  "diseases": "depression",
  "position": "full body, head",
  "primary_symptoms": "change in sleeping habits, change in eating habits, loss of interest in activities, guilt, decreased energy, suicidal thoughts  ",
  "time": "",
  "unique": "",
  "emergency": "",
  "home": ""
},
{
  "id": "14",
  "diseases": "eczema",
  "category":"musculoskeletal",
  "position": "hand, face, knee, elbow",
  "primary_symptoms": "redness, itchiness, difficulty breathing",
  "time": "chronic",
  "unique": "dry, asthma diagnosis",
  "emergency": "decreases quality of life, change in color vision",
  "home": "avoid allergic triggers, avoid chemical irritants (clothing, chemicals), keep skin moisturized, manage stress"
},
{
  "id": "15",
  "diseases": "enlarged prostate",
  "category": "genitourinary",
  "position": "groin",
  "primary_symptoms": "difficulty urinating",
  "time": "chronic",
  "unique": "change in urination frequency, difficulty urinating",
  "emergency": "lower back pain, burning with urination",
  "home": "contact your doctor"
},
{
  "id": "16",
  "diseases": "food poisoning",
  "category": "gastrointestinal",
  "position": "stomach, anus, mouth",
  "primary_symptoms": "diarrhea, vomiting",
  "time": "",
  "unique":"" ,
  "emergency":"" ,
  "home": ""
},
{
  "id": "16",
  "diseases": "gallstones",
  "category":"gastrointestinal",
  "position": "stomach, shoulder, upper back",
  "primary_symptoms": "pain after eating, pain",
  "time": "acute",
  "unique": "worse after fatty foods",
  "emergency": "confusion, skin yellowing, high fever, urine darkening, skin rash",
  "home": "go to the emergency room, avoid fatty foods"
},
{
  "id": "17",
  "diseases": "Hand foot mouth disease",
  "category":"infection",
  "position": "full body, hands, feet, throat",
  "primary_symptoms": "rash, fever, itchiness",
  "time":"" ,
  "unique": "",
  "emergency": "",
  "home": ""
},
{
  "id": "18",
  "diseases": "heart attack",
  "category":"cardiovascular",
  "position": "chest, back, neck, arm, stomach",
  "primary_symptoms": "pain, anxiety, difficulty breathing, sweating",
  "time": "chronic",
  "unique": "squezing chest pain, shortness of breath, left arm pain, neck pain",
  "emergency": "chest pain, arm pain, shortness of breath, nausea, neck pain",
  "home": "baby aspirin, call emergency services"
},
{
  "id": "19",
  "diseases": "heart failure",
  "category":"cardiovascular",
  "position": "stomach, legs, chest, full body",
  "primary_symptoms": "swelling, cough, difficulty breathing, decreased energy",
  "time": "chronic",
  "unique": "leg swelling, shortness of breath when lying flat, sleeping with head elevated",
  "emergency": "shortness of breath, weight loss, blood in cough, chest pain, neck pain, fainting",
  "home": "decrease salt intake, exercise, avoid nicotine, avoid tobacco, avoid alcohol, make an appointment with your doctor"
},
{
  "id": "20",
  "diseases": "hemorrhoids",
  "category":"gastrointestinal",
  "position": "anus",
  "primary_symptoms": "blood in the toilet",
  "time": "chronic",
  "unique": "bright red blood in toilet, stomach pain",
  "emergency": "weight loss, dark blood in toilet",
  "home": "eat more fiber, avoid excess strain when using the restroom"
},
{
  "id": "21",
  "diseases": "Herpes",
  "category":"infection",
  "position": "groin, mouth",
  "primary_symptoms": "rash",
  "time": "",
  "unique":"" ,
  "emergency":"" ,
  "home": ""
},
{
  "id": "22",
  "diseases": "hyperthyroid",
  "category": "endocrine",
  "position": "full body, throat, neck, leg",
  "primary_symptoms": "decreased energy, weakness, weight gain, swelling",
  "time": "chronic",
  "unique": "eye bulging, heart palpitations, heat intolerance, weight loss",
  "emergency": "chest pain, loss of consciousness, bone breakeage, change in menstrual cycle, depression", 
  "home": "avoid alcohol, avoid recreational drug usage, avoid stress"
},
{
  "id": "23",
  "diseases": "Inflammatory bowel disease (IBD)",
  "category": "gastrointestinal",
  "position": "stomach, mouth, anus",
  "primary_symptoms": "blood in the toilet, pain",
  "time": "chronic",
  "unique": "blood in toilet, stomach pain, diarrhea, constipation, nausea, cramps",
  "emergency": "blood in the toilet, weight loss, yellowing of the skin, high fever, night-time diarrhea",
  "home": "eat more fiber, stay hydrated, avoid certain foods if reactive"
},
{
  "id": "24",
  "diseases": "Influenza",
  "category":"infection",
  "position": "nose, throat, head, full body",
  "primary_symptoms": "sneezing, cough, congestion, runny nose, fever",
  "time":"",
  "unique":"",
  "emergency": "",
  "home": ""
},
{
  "id": "25",
  "diseases": "Irritable bowel syndrome (IBS)",
  "category":"gastrointestinal",
  "position": "stomach, anus",
  "primary_symptoms": "pain, diarrhea",
  "time": "chronic",
  "unique": "frequent diarrhea, stomach pain, stomach cramping after certain foods",
  "emergency": "blood in toilet, weight loss, fever, night-time diarrhea",
  "home": "eat more fiber, rehydrate, avoid certain foods if reactive (lactose, gluten, honey, apple, corn syrup) avoid stress"
},
{
  "id": "26",
  "diseases": "kidney stones",
  "category":"genitourinary",
  "position": "stomach, groin, lower back",
  "primary_symptoms": "blood in the toilet",
  "time": "chronic",
  "unique": "blood in the urine, back pain, pelvic pain, difficulty urinating",
  "emergency": "weight loss, blood in the urine, fever",
  "home": "hydration, otc painkillers"
},
{
  "id": "27",
  "diseases": "laryngitis",
  "category": "respiratory",
  "position": "throat, nose",
  "primary_symptoms": "loss of voice, fever",
  "time":"",
  "unique": "",
  "emergency": "",
  "home": ""
},
{
  "id": "28",
  "diseases": "Lupus",
  "category": "infection",
  "position": "skin, lower back, eyes, heart, chest, stomach",
  "primary_symptoms": "rash",
  "time": "chronic",
  "unique": "face rash, random organ involvement, arthritis, fever, weakness",
  "emergency": "seizures, confusion, neck stiffness, shortness of breath, blood in the urine",
  "home": "place sunscreen, avoid nicotine, avoid tobacco, contact your doctor"
},
{
  "id": "29",
  "diseases": "lyme disease",
  "category": "infection",
  "position": "skin, joints, full body, chest",
  "primary_symptoms": "bulls-eye rash, pain",
  "time": "",
  "unique":"" ,
  "emergency": "",
  "home": ""
},
{
  "id": "30",
  "diseases": "migraine",
  "category": "neurological",
  "position": "head",
  "primary_symptoms": "pain, dizziness, nausea, vomiting, sound sensitivity",
  "time":"",
  "unique": "",
  "emergency": "",
  "home": ""
},
{
  "id": "31",
  "diseases": "mononucleosis kissing disease",
  "category": "infection",
  "position": "full body, throat",
  "primary_symptoms": "fatigue, swollen lymph nodes, fever, sore throat, pain",
  "time":"" ,
  "unique":"" ,
  "emergency": "",
  "home": ""
},
{
  "id": "32",
  "diseases": "myasthenia gravis",
  "category":"neurological",
  "position": "face, full body, eyes",
  "primary_symptoms": "weakness with repetitive movements, weakness, word slurring, tunnel vision",
  "time": "chronic",
  "unique": "weakness with repetitive movements, difficulty opening eyes",
  "emergency": "choking",
  "home": "contact your doctor"
},
{
  "id": "33",
  "diseases": "osteoarthritis",
  "category": "musculoskeletal",
  "position": "hand, leg, foot, knee",
  "primary_symptoms": "weakness, pain, difficulty walking, joint pain",
  "time": "chronic",
  "unique": "swelling of joints at fingertips, pain at end of day",
  "emergency": "bone breakage, difficulty walking",
  "home": "otc painkillers, light exercise"
},
{
  "id": "34",
  "diseases": "otitis externa",
  "category": "infection",
  "position": "ear",
  "primary_symptoms": "pain",
  "time": "",
  "unique": "",
  "emergency":"" ,
  "home": ""
},
{
  "id": "35",
  "diseases": "pancreatitis",
  "category": "gastrointestinal",
  "position": "stomach, upper back, skin",
  "primary_symptoms": "pain, appetite loss, yellowing of skin, yellowing of eyes",
  "time":"",
  "unique":"",
  "emergency":"",
  "home": ""
},
{
  "id": "36",
  "diseases": "panic attack",
  "category": "neurological",
  "position": "chest, head, stomach",
  "primary_symptoms": "confusion, palpitations, headache",
  "time": "",
  "unique":"",
  "emergency":"" ,
  "home": ""
},
{
  "id": "37",
  "diseases": "pneumonia",
  "category": "respiratory",
  "position": "lungs, head",
  "primary_symptoms": "cough, fever, shortness of breath, mucous ",
  "time": "",
  "unique": "",
  "emergency": "",
  "home": ""
},
{
  "id": "38",
  "diseases": "pregnancy",
  "category": "endocrine",
  "position": "stomach, full body",
  "primary_symptoms": "vomiting, swelling, weight gain, vomiting, low energy, lower back pain, irritability",
  "time": "chronic",
  "unique": "leg swelling, lower back pain, missed period",
  "emergency": "blood in toilet, fever, stomach cramping, weight loss",
  "home": "take otc pregrancy prenatal care vitamins, stay hydrated, exercise, maintain healthy lifestyle"
},
{
  "id": "39",
  "diseases": "psoriasis",
  "category": "",
  "position": "hand, face, knee, elbow",
  "primary_symptoms": "itchiness, rash, redness, warmth",
  "time": "chronic",
  "unique": "pitting of the nails, discoloration of the nails, brittleness of the nails, white scaly skin, elbow involvement, scalp involvement, back involvement, knee involvement",
  "emergency": "decreases quality of life, change in color to white or red, spread, blood",
  "home": "moisturize ,vitamin-d, avoid nicotine use, avoid alcohol use, sunscreen, regular physical activity"
},
{
  "id": "40",
  "diseases": "pulmonary embolism",
  "category": "",
  "position": "chest",
  "primary_symptoms": "difficulty breathing, chest pain, shortness of breath",
  "time": "chronic",
  "unique": "bloody cough, difficulty breathing, chest pain",
  "emergency": "loss of consciousness, blood in cough, difficulty breathing",
  "home": "avoid long periods of not moving, monitor blood oxygen levels"
},
{
  "id": "41",
  "diseases": "recent swimming",
  "category": "",
  "position": "ear",
  "primary_symptoms": "pain, fever",
  "time": "",
  "unique":"" ,
  "emergency":"" ,
  "home": ""
},
{
  "id": "42",
  "diseases": "Reflux",
  "category": "",
  "position": "throat, chest, stomach",
  "primary_symptoms": "cough",
  "time": "acute",
  "unique": "burping, regurgitation, heartburn worse when lying down",
  "emergency": "difficulty breathing, weight loss, blood",
  "home": "avoid alcohol consumption, avoid nicotine, avoid tobacco, lose weight, take otc antacids"
},
{
  "id": "43",
  "diseases": "Rheumatoid arthritis",
  "category": "",
  "position": "hand, leg, foot, knee, neck",
  "primary_symptoms": "pain, fever, weakness",
  "time": "chronic",
  "unique": "swelling of joints closest to wrist, morning pain",
  "emergency": "neck stiffness, limb numbness, skin ulcers, difficulty breathing, chest pain, neck pain, infections, stomach swelling",
  "home": "otc painkillers"
},
{
  "id": "44",
  "diseases": "schizophrenia",
  "category": "",
  "position": "full body, head",
  "primary_symptoms": "visual hallucinations, depression, change in energy levels, confusion, audio hallucinations, anxiety",
  "time": "",
  "unique": "",
  "emergency": "",
  "home": ""
},
{
  "id": "45",
  "diseases": "sinus infection",
  "category": "",
  "position": "head",
  "primary_symptoms": "headache, congestion, pressure, runny nose",
  "time": "",
  "unique": "",
  "emergency": "" ,
  "home": ""
},
{
  "id": "46",
  "diseases": "skin cancer",
  "category": "",
  "position": "skin, feet, upper back, head",
  "primary_symptoms": "abnormal color, abnormal shape, abnormal growth",
  "time": "chronic",
  "unique": "bleeding mole, itchiness",
  "emergency": "bleeding mole, weight loss, other abnormal moles",
  "home": "sunscreen, avoid scratching"
},
{
  "id": "47",
  "diseases": "strep throat",
  "category": "",
  "position": "throat, nose",
  "primary_symptoms": "sore throat, congestion, fever",
  "time": "",
  "unique": "",
  "emergency": "",
  "home": ""
},
{
  "id": "48",
  "diseases": "stroke",
  "category": "",
  "position": "arm, leg, face, head, face, full body",
  "primary_symptoms": "weakness, word slurring, strange smells, sweating",
  "time": "chronic",
  "unique": "slurring of speech, arm weakness, leg weakness, facial droop",
  "emergency": "slurring of speech, arm weakness, leg weakness, facial droop, difficulty walking, difficulty breathing",
  "home": "exercise, avoid nicotine, avoid tobacco, avoid alcohol, avoid recreational drug usage "
},
{
  "id": "49",
  "diseases": "Syphillis",
  "category": "",
  "position": "groin",
  "primary_symptoms": "painless ulcer, discharge from urethra, rash, warts",
  "time":"" ,
  "unique": "",
  "emergency": "",
  "home": ""
},
{
  "id": "50",
  "diseases": "tension headache",
  "category": "",
  "position": "head",
  "primary_symptoms": "pain, dizziness, nausea, vomiting",
  "time": "",
  "unique": "",
  "emergency": "",
  "home": ""
  },
{
  "id": "51",
  "diseases": "testicular cancer",
  "category": "",
  "position": "groin, chest",
  "primary_symptoms": "pain, testicular lump",
  "time": "chronic",
  "unique": "testicular lump, testicular pain",
  "emergency": "vomiting, lower back pain, difficulty breathing, bone pain",
  "home": "routine testicular palpation"
},
{
  "id": "52",
  "diseases": "Tuberculosis",
  "category": "",
  "position": "chest",
  "primary_symptoms": "cough, weight loss, fever, night sweats, shortness of breath",
  "time": "",
  "unique": "" ,
  "emergency": "",
  "home": ""
},
{
  "id": "53",
  "diseases": "UTI",
  "category": "",
  "position": "groin",
  "primary_symptoms": "increased frequency of urination, burning on urination",
  "time": "",
  "unique": "",
  "emergency":"" ,
  "home": ""
}
]

